/*
 * Copyright 2026 The Vida Project Authors.
 * Licensed under the Apache License, Version 2.0.
 */
package dev.vida.installer.launchers.prism;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;

/**
 * Сборщик {@code instance.cfg} — INI-файла, который Prism/MultiMC используют
 * для per-instance настроек.
 *
 * <p>Формат — Java-Properties-совместимый, на стороне Prism парсится Qt
 * {@code QSettings::IniFormat}. Поддерживает {@code key=value}, escape через
 * {@code \}, строки в двойных кавычках.
 *
 * <p>Минимум обязательных полей для нового instance'а:
 * <ul>
 *   <li>{@code InstanceType=OneSix} — иначе лаунчер посчитает instance
 *       «битым» и не даст запустить.</li>
 *   <li>{@code name=&lt;display name&gt;}</li>
 * </ul>
 *
 * <p>Для MultiMC и старых Prism (без {@code +agents}) дополнительно пишем
 * {@code OverrideJavaArgs=true} и {@code JvmArgs=-javaagent:&lt;path&gt;}.
 */
public final class PrismInstanceCfg {

    private final Map<String, String> keys = new LinkedHashMap<>();

    public PrismInstanceCfg(String instanceDisplayName) {
        Objects.requireNonNull(instanceDisplayName, "instanceDisplayName");
        keys.put("InstanceType", "OneSix");
        keys.put("name", instanceDisplayName);
        keys.put("iconKey", "default");
        keys.put("notes", "Installed by Vida installer.");
        keys.put("OverrideCommands", "false");
        keys.put("OverrideConsole", "false");
        keys.put("OverrideJavaLocation", "false");
        keys.put("OverrideJavaArgs", "false");
        keys.put("OverrideMemory", "false");
        keys.put("lastLaunchTime", "0");
        keys.put("totalTimePlayed", "0");
        keys.put("ManagedPack", "false");
    }

    /** Включает override и прописывает дополнительные JVM-аргументы. */
    public PrismInstanceCfg withJvmArgs(String jvmArgs) {
        Objects.requireNonNull(jvmArgs, "jvmArgs");
        keys.put("OverrideJavaArgs", "true");
        keys.put("JvmArgs", jvmArgs);
        return this;
    }

    /** Произвольный key=value (при коллизии перезаписывает). */
    public PrismInstanceCfg set(String key, String value) {
        keys.put(Objects.requireNonNull(key), Objects.requireNonNull(value));
        return this;
    }

    /** Сериализует в строку, пригодную для записи в {@code instance.cfg}. */
    public String render() {
        StringBuilder sb = new StringBuilder(256);
        sb.append("# Generated by Vida installer\n");
        for (Map.Entry<String, String> e : keys.entrySet()) {
            sb.append(e.getKey()).append('=').append(escape(e.getValue())).append('\n');
        }
        return sb.toString();
    }

    /**
     * Properties-style escaping. Prism не требует escape для обычных
     * символов, но мы страхуемся от пробелов в путях (Windows), обратных
     * слэшей и знаков равенства внутри значения.
     */
    static String escape(String v) {
        StringBuilder sb = new StringBuilder(v.length() + 4);
        for (int i = 0; i < v.length(); i++) {
            char c = v.charAt(i);
            switch (c) {
                case '\\' -> sb.append("\\\\");
                case '\n' -> sb.append("\\n");
                case '\r' -> sb.append("\\r");
                case '\t' -> sb.append("\\t");
                default   -> sb.append(c);
            }
        }
        return sb.toString();
    }
}
